CREATE SCHEMA auth;

CREATE TABLE auth.user_account (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username        varchar(40) NOT NULL,
    password        text,
    CONSTRAINT unique_user_account UNIQUE(username)
);
